#!/bin/bash

DIR=`dirname $0`/..
MYPATH=$DIR

if [ $# -lt 1 ]
then
  echo "$0 error: must supply argument"
  exit 1
fi

if [ ! -x $NODEPATH/node ] 
then
  echo "$0 error: node command not found"
  exit 1
fi

ASK=0
if [ $1 = '-c' ] 
then
  ASK=1
fi

$NODEPATH/node $MYPATH/index.js 0 $@

declare -a prefixes 
BODY=''
for NAME in $@
do
  if [ $NAME = '-c' ]
  then
    continue
  fi
  PRE=`echo $NAME | tr 'A-Z' 'a-z'`
  RESULTS=`$MYPATH/scripts/listnew "$MYPATH/data/${PRE}-data" "$MYPATH/data/${PRE}-data-all"`
  if [ -n "$RESULTS" ]
  then
    echo $PRE delta results: `echo "$RESULTS" | wc -l`
    FMT_RESULTS=$(
      echo "$RESULTS" | \
      while read LINE
      do
        A=`echo "$LINE" | cut -f1`
        B=`echo "$LINE" | cut -f2`
        C=`echo "$LINE" | cut -f3`
        echo $A \(ny: $C\)
        paste <(echo "") <(echo "$B" | fold -sw 40) | expand -t3
      done
    )

    BODY+="$NAME";
    BODY+='\n'
    BODY+="$FMT_RESULTS";
    BODY+='\n\n'

    prefixes+=($PRE)
  else 
    echo $PRE delta results: 0
  fi
done

# merges data files into their respective "all" files
if [ $ASK -gt 0 ]
then
  $MYPATH/scripts/dedupe -c ${prefixes[@]}
else
  $MYPATH/scripts/dedupe ${prefixes[@]}
fi

# Email results
SUBJECT=`date '+Scrape Results (%D %k:%M)'`
if [ -n "$BODY" ] 
then
  # printf interprets '\n' as actual newline. The command substitution is wrapped in double-quotes again to keep the 
  # result in one string
  $MYPATH/scripts/mailgunsend jk jookang22@gmail.com "$SUBJECT" "`printf "%b" "$BODY"`"

else
  $MYPATH/scripts/mailgunsend jk jookang22@gmail.com "$SUBJECT" "No updates"

fi

exit 0
  
